### ISSUE TITLE
Do `SWAP_PREAMBLE_VOID` and `SWAP_PREAMBLE_TEMPLATE_VOID` miss a return?

### ISSUE THREAD

**Issue by dpinthinker** [UWSysLab/marvin-art#1]
Should a `return; \` be added after `stub->UnlockTableEntry();` in macro `SWAP_PREAMBLE_VOID` and `SWAP_PREAMBLE_TEMPLATE_VOID`?

https://github.com/UWSysLab/marvin-art/blob/2c1c1d7a0b1845a1ba62456c388afc1aaf2e09a7/runtime/mirror/object.h#L57-L66

https://github.com/UWSysLab/marvin-art/blob/2c1c1d7a0b1845a1ba62456c388afc1aaf2e09a7/runtime/mirror/object.h#L68-L77

**Comment by nlebeck** [comment]
It's been years since I looked at this code, but I think the lack of `return` is intentional. Those are macros, not functions. If the macros included a return statement, any function that included them would return early instead of executing normally after invoking the code in the macros.

**Comment by nlebeck** [comment]
Hmm, it's been years since I looked at this code, but you might be right! (If so, maybe I didn't spot this mistake because all of our experiments happened to first access swapped-out objects via a non-void method?)

**Comment by dpinthinker** [comment]
Hi Niel, I have made a fix, could you help to review and merge it?

**Comment by nlebeck** [comment]
I don't have the bandwidth, context, or testing setup to review changes to this repository, and I'd prefer to leave it as a snapshot of the code that was used in experiments for our ATC paper (bugs and all). Feel free to fork the repo and modify it though!

**Comment by dpinthinker** [comment]
OK，I will close this issue and pull request. Thank you so much！
